### ISSUE TITLE
Bug Fix: User should be able to create / join a game after they have already finished playing one.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#154]

**Comment by ninanni** [comment]
fixed with commit dbae4f40999605246ab0b9b554ffb60746adf58e

https://github.com/sopra-fs23-group-09/SpyWithMyLittleEye_server/blob/dbae4f40999605246ab0b9b554ffb60746adf58e/src/main/java/ch/uzh/ifi/hase/soprafs23/service/UserService.java#L50-L52

https://github.com/sopra-fs23-group-09/SpyWithMyLittleEye_server/blob/dbae4f40999605246ab0b9b554ffb60746adf58e/src/main/java/ch/uzh/ifi/hase/soprafs23/service/LobbyService.java#L113-L121
